package pl.lodz.p.it.spjava.e11.huntingBook.model.enums;

public enum AnimalType {
    ELK_MALE_SELECTIVE,
    ELK_MALE_GAME,
    ELK_FEMALE,
    ELK_CALF,
    RED_DEER_MALE_SELECTIVE,
    RED_DEER_MALE_GAME,
    RED_DEER_FEMALE,
    RED_DEER_CALF,
    FALLOW_DEER_MALE_SELECTIVE,
    FALLOW_DEER_MALE_GAME,
    FALLOW_DEER_FEMALE,
    FALLOW_DEER_CALF,
    ROE_DEER_MALE_SELECTIVE,
    ROE_DEER_MALE_GAME,
    ROE_DEER_FEMALE,
    ROE_DEER_CALF,
    BOAR_MALE,
    BOAR_FEMALE,
    MOUFLON_MALE_SELECTIVE,
    MOUFLON_MALE_GAME,
    MOUFLON_FEMALE,
    MOUFLON_CALF,
    FOX,
    HARE,
    PHEASANT,
    PARTRIDGE,
    GOOSE,
    DUCK

}
